### ISSUE TITLE
Rewrite serialization writers to be asynchronous

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/dart_kiota#29]
The `Parsable` defines a method `serialize` that returns a `FutureOr<void>` and receives a `SerializationWriter`.

When serializing nested objects, this `serialize` method gets called from within `write*` methods of the `SerializationWriter`s.

The problem is that the `write*` methods are not asynchronous and cannot await the `FutureOr<void>` returned from the `serialize` method of the `Parsable`.

To mitigate this, I want to rewrite all `write*` methods in the serialization writers to be asynchronous.

**Comment by baywet** [comment]
@ricardoboss I missed a few changes here. I would understand why the getSerializedContent might need to be async. But all the write methods? Can you provide a call stack that illustrates the need? We haven't had that need in any other language.

**Comment by ricardoboss** [comment]
Okay, I hope this makes sense:

1. The [`Parsable`](https://github.com/ricardoboss/dart_kiota/blob/94cb95d41b3a29b9de49446e362f152b6afdcf46/packages/kiota_abstractions/lib/src/serialization/parsable.dart) has a method `serialize`
  - its return type is `FutureOr<void>` (as opposed to `Future<void>`), so implementations may choose to implement it synchronously
  - it may also be implemented asynchronously, if serializing the concrete implementation requires awaiting something
2. The [`MultipartBody`](https://github.com/ricardoboss/dart_kiota/blob/94cb95d41b3a29b9de49446e362f152b6afdcf46/packages/kiota_abstractions/lib/src/multipart_body.dart#L71) implements this method asynchronously, because if the any part has a value of type `Stream<int>` (that is, a stream of bytes like a file), it must use `await` to turn this stream to a list that can then be written.
3. In [`FormSerializationWriter`](https://github.com/ricardoboss/dart_kiota/blob/9601c1f223b5012c02b27239aa6c566cd9b9aea9/packages/kiota_serialization_form/lib/src/form_serialization_writer.dart#L162), this `serialize` method is called, but since the interface doesn't allow it to be implemented asynchronously, it can't `await` the result.

Therefore the `writeObjectValue` method must allow async implementations using a return type of `FutureOr<void>` as opposed to just `void`.

I hope this explains my thinking. Maybe this is something that is Dart specific because of the `Stream` type.

**Comment by baywet** [comment]
Thanks for the additional context here.
My worry is that all those additional Futures are going to have a serious performance impact. And I'm not even sure if dart has a concept similar to the cancellation token in dotnet, which would impact the API surface even further.

If we [look at the text serialization writer](https://github.com/ricardoboss/dart_kiota/blob/983e5986968308e164a922d9c46ba55ae5137aa6/packages/kiota_serialization_text/lib/src/text_serialization_writer.dart#L22) we can see the implementation is synchronous.

Which then means the only reason why serialize in multi part body needs to be async is [because of the stream case](https://github.com/ricardoboss/dart_kiota/blob/94cb95d41b3a29b9de49446e362f152b6afdcf46/packages/kiota_abstractions/lib/src/multipart_body.dart#L120) as you've outlined.

Could we remove that case for now, and require the caller to make the async conversion of stream to list in the application code whenever they add the part instead?
